language: bash
matrix:
  include:
    - os: linux
      script: make travis
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
      env:
         - COMPILER="CC=gcc-5 && CXX=g++-5"
      before_install: eval "${COMPILER}"
      script: make travis
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
         - COMPILER="CC=gcc-7 && CXX=g++-7"
      before_install: eval "${COMPILER}"
      script: make travis
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - gcc-9
      env:
         - COMPILER="CC=gcc-9 && CXX=g++-9"
      before_install: eval "${COMPILER}"
      script: make travis
    - os: linux
      compiler: clang
      script: make travis
    - os: osx
      script: make travis
    - os: osx
      osx_image: xcode10
      script: make travis
    - os: windows
      install:
        - choco install mingw
        - choco install ruby
        - gem install colorize
        - gem install fileutils
        - gem install zip
      env:
        - CMAKE_PATH="/c/Program Files/CMake/bin"
      script:
        - export PATH=$CMAKE_PATH:$PATH
        - rake build_win
        - rake run_win
