set(CPACK_PACKAGE_VENDOR "Enrico Bertolazzi")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Clothoid generation tools")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_CONTACT "Enrico Bertolazzi enrico.bertolazzi@unitn.it")

include(CPack)