clc;

NAMES = { 'spline2d' } ;
CFILES = ['../srcs/SplineAkima.cc ' ...
          '../srcs/SplineAkima2D.cc ' ...
          '../srcs/SplineBessel.cc ' ...
          '../srcs/SplineBiCubic.cc ' ...
          '../srcs/SplineBiQuintic.cc ' ...
          '../srcs/SplineBilinear.cc ' ...
          '../srcs/SplineConstant.cc ' ...
          '../srcs/SplineCubic.cc ' ...
          '../srcs/SplineCubicBase.cc ' ...
          '../srcs/SplineHermite.cc ' ...
          '../srcs/SplineLinear.cc ' ...
          '../srcs/SplinePchip.cc ' ...
          '../srcs/SplineQuintic.cc ' ...
          '../srcs/SplineQuinticBase.cc ' ...
          '../srcs/SplineSet.cc ' ...
          '../srcs/Splines.cc ' ...
          '../srcs/SplinesBivariate.cc ' ...
          '../srcs/SplinesCinterface.cc ' ...
          '../srcs/SplinesUnivariate.cc ' ] ;

disp('---------------------------------------------------------');
for k=1:1
  N=NAMES{k} ;
  fprintf(1,'Compiling: %s\n',N) ;

  CMD = ['mex -I../srcs -I../srcs_utils -output ./',N,' -largeArrayDims mex_',N,'.cc ',CFILES] ;
  if isunix
    if ismac
      CMD = [CMD, ' -lstdc++ CXXFLAGS="\$CXXFLAGS -Wall -O2 -g0"'] ;
    else
      CMD = [CMD, ' -lstdc++ CXXFLAGS="\$CXXFLAGS -Wall -O2 -g0"'] ;
    end
  elseif ispc
  end
  disp(CMD);
  eval(CMD);
end
disp('----------------------- DONE ----------------------------');
