clc;

NAMES = { 'SplineVecMexWrapper', ...
          'SplineSetMexWrapper', ...
          'Spline1DMexWrapper', ...
          'Spline2DMexWrapper' };
CFILES = ['../src/SplineAkima.cc ' ...
          '../src/SplineAkima2D.cc ' ...
          '../src/SplineBessel.cc ' ...
          '../src/SplineBiCubic.cc ' ...
          '../src/SplineBiQuintic.cc ' ...
          '../src/SplineBilinear.cc ' ...
          '../src/SplineConstant.cc ' ...
          '../src/SplineCubic.cc ' ...
          '../src/SplineCubicBase.cc ' ...
          '../src/SplineHermite.cc ' ...
          '../src/SplineLinear.cc ' ...
          '../src/SplinePchip.cc ' ...
          '../src/SplineQuintic.cc ' ...
          '../src/SplineQuinticBase.cc ' ...
          '../src/SplineSet.cc ' ...
          '../src/SplineVec.cc ' ...
          '../src/Splines.cc ' ...
          '../src/SplinesBivariate.cc ' ...
          '../src/SplinesCinterface.cc ' ...
          '../src/SplinesUnivariate.cc ' ];

disp('---------------------------------------------------------');
for k=1:4
  N=NAMES{k};
  fprintf(1,'Compiling: %s\n',N);
  CMD = ['mex -DSPLINES_DO_NOT_USE_GENERIC_CONTAINER -I../src -I../include -output ../lib_matlab/',N,' -largeArrayDims ../src_matlab_interface/mex_',N,'.cc ',CFILES];
  if isunix
    CMD = [CMD, ' CXXFLAGS="\$CXXFLAGS -lstdc++ -Wall -O2 -g0"'];
  elseif ispc
  end
  %disp(CMD);
  eval(CMD);
end
disp('----------------------- DONE ----------------------------');
